base:
  config:
    db:
      dbtype: mysql
      dbname: onlinejudge_oauth2
      hostname: localhost
      port: 3306
    nacos:
      hostname: 39.103.218.148
      port: 8848
    redis:
      hostname: 39.103.218.148
      port: 6379


spring:
  application:
    name: onlinejudge-oauth2
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:${base.config.db.dbtype}://${base.config.db.hostname}:${base.config.db.port}/${base.config.db.dbname}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: ${base.config.redis.hostname}
    port: ${base.config.redis.port}
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8

dubbo:
  scan:
    base-packages: cn.edu.nciae.onlinejudge.oauth2.controller, cn.edu.nciae.onlinejudge.oauth2.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

server:
  port: 20001

management:
  endpoints:
    web:
      exposure:
        include: "*"

business:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret
    url_oauth_token: http://localhost:${server.port}/oauth/token
